### ISSUE TITLE
Use a data serialization language for the config file or support double quotes

### ISSUE THREAD

**Issue by scalp42** [logdna/logdna-agent#100]
Hi folks,

We just tried to test drive LogDNA and first issue we ran into is that the config file is some kind of INI-like (bad idea).

Second issue is that if you have globs in your logdir, then you need to use double quotes which is fine but you can't exactly use double quotes everywhere say for example the `key` which just bit us:

```
root@default-ubuntu-1804:/var/log# cat /etc/logdna.conf
# This file is handled by Chef in wo-logdna::config

logdir = "/var/log/apt/history.log,/var/log/logdna-agent.log"
key = "mykey"
tags = "kitchen"
autoupdate = 0
hostname = "default-ubuntu-1804"
```

Which leads to the agent taking the double quotes:

```
[190612 00:50:16] logdna-agent 1.5.6 started on "default-ubuntu-1804" (10.0.2.15)
[190612 00:50:16] Authenticating API Key with api.logdna.com (SSL)...
[190612 00:50:16] Auth error: 401: {"error":"Unable to authenticate key: \"a8316685af8efac342a846494aab5dcf\"","code":"Rejected","status":"error"}
```

Any plans to move say to TOML, JSON or anything like? It'll make it much easier to dump the config through configuration management as well so that instead of something like this:

```
# This file is handled by Chef in <%= @cookbook %>::<%= @recipe %>

<% @config.each do |k, v| %>
<% if v.is_a?(Integer) %>
<%= k %> = <%= v %>
<% else %>
<%= k %> = "<%= v %>"
<% end %>
<% end %>
```

We can simply `JSON.dump(fancy_logdna_config)` for the config template.

Thanks!

**Comment by scalp42** [comment]
Round 2, it seems to be breaking use double quotes on logdir as well:

```
logdir = "/var/log/apt/history.log,/var/log/logdna-agent.log"
```

```
[190612 01:00:20] Error accessing "/var/log/apt/history.log: Error: ENOENT: no such file or directory, stat '"/var/log/apt/history.log'
[190612 01:00:20] Error accessing /var/log/logdna-agent.log": Error: ENOENT: no such file or directory, stat '/var/log/logdna-agent.log"'
```

I'm assuming you need to specify each file within double quotes or maybe you can specify `logdir` multiple times:

```
-logdir = "/var/log/apt/history.log,/var/log/logdna-agent.log"
+logdir = "/var/log/apt/history.log"
+logdir = "/var/log/logdna-agent.log"
```

```
[190612 01:05:07] Connected to logs.logdna.com:443 (52.168.140.197) (SSL)
[190612 01:05:07] Error accessing "/var/log/logdna-agent.log": Error: ENOENT: no such file or directory, stat '"/var/log/logdna-agent.log"'
```

Try each string:

```
-logdir = "/var/log/apt/history.log"
-logdir = "/var/log/logdna-agent.log"
+logdir = "/var/log/apt/history.log","/var/log/logdna-agent.log"
```

```
[190612 01:07:04] Error accessing "/var/log/apt/history.log": Error: ENOENT: no such file or directory, stat '"/var/log/apt/history.log"'
[190612 01:07:04] Error accessing "/var/log/logdna-agent.log": Error: ENOENT: no such file or directory, stat '"/var/log/logdna-agent.log"'
```

**Comment by dchai76** [comment]
Anthony,

Apologies, but there's an error in our documentation - the double quotes are only needed when specifying glob patterns in cli commands, namely when you call `sudo node index.js -d`. If you're editing the conf file directly, you don't need (and in fact can't use) double quotes anywhere. So `logdir = /var/log/apt/history.log,/var/log/logdna-agent.log` should work. Let me know if it does, and really sorry for the confusion.

> Any plans to move say to TOML, JSON or anything like? 

We'll put that under consideration, but we probably won't be making any changes to the conf file format soon.

**Comment by scalp42** [comment]
@dchai76 thanks for the feedback.

Adding to it, assume we want to ship everything in `/var/log` but not what's inside `/var/log/artifacts/*`, how can you do that?

**Comment by dchai76** [comment]
This is in the documentation at https://github.com/logdna/logdna-agent#options

`logdir`: sets the paths that the agent will monitor for new files, separate multiple paths using ,, supports glob patterns + specific files. By default this option is set to monitor .log and extensionless files under /var/log/.
`exclude`: excludes files that otherwise would've matched logdir, separate multiple excludes using ,, supports glob patterns + specific files

`/var/log` is tracked by default so you just need to have `exclude = /var/log/artifacts/*`.

**Comment by scalp42** [comment]
I see, we were trying to pass a directory directly. Got it.

I'm going to close the issue as it won't be resolved.

Thanks for the feedback.
