### ISSUE TITLE
runtime memory usage

### ISSUE THREAD

**Issue by diwu1989** [logdna/logdna-agent#11]
what is the runtime memory usage of this daemon if its left running for dozens of days?
could there be a mechanism to run the log collection in a worker process and periodically respawn that process to make sure there's no long term memory leak?

**Comment by baronomasia** [comment]
Good question - it really depends on your logging volume. If your logging volume isn't huge (e.g. over 1000 lines/sec), typically the agent should use no more than 25-75 MB of RAM. 

If you do log more than 1000 lines/sec, email support@logdna.com and we'll turn a different transport mechanism rated for up to 100,000 lines/sec.
