### ISSUE TITLE
Include log file from non traditional locations

### ISSUE THREAD

**Issue by PXMYH** [logdna/logdna-agent#118]
Hi I'm trying to include application log files from folder other than `/var/log` and `/etc` running in Kubernetes Pods. I understand there might be a way to leverage `Volumes` and `VolumeMount` as listed in https://github.com/logdna/logdna-agent/blob/master/logdna-agent-v2.yaml, but when I added my application log under `/home/<my_app>/logs` in each pod to logdna-agent-v2.yaml and deploy the DaemonSet, it just created the folder without ingesting any logs from application pods.

Looking through the code, seems like you can specify directory for Linux and Windows via `logdir` but not for Kubernetes, is there any way to achieve ingesting application logs from non-traditional locations in K8s?

My setup:
LogDNA agent v2 for Kubernetes deployment

Thanks!

**Comment by CJP10** [comment]
A brief overview of how the agent works.

The agent mounts in the node's `/var/log/` directory and recursively tails the files within that directory.
K8s will write all your pods stdour/err to the node's `/var/log/pods/`.
No directory inside your pod is monitored by the agent. The agent only works on the node's filesystem not on your pod(s).

I would recommend the following.
Mount `/var/log/<app_name>` to `/home/<my_app>/logs` in your application pod.
This will bind mount `/home/<my_app>/logs` in your pod to the node's `/var/log/<app_name>`.
The agent will automatically pick up the new directory and you should be on your way.

Let me know if this wasn't clear enough. In general, I would recommend that you write to stdout/err. That's the supported method of logging but if that's not an option the above should do you fine.

**Comment by sgwilson2674** [comment]
Closing the issue due to inactivity. If additional questions remain, please open another issue and we’ll be sure to respond. 
If additional kubernetes questions, please visit this repo which is used for our k8s agent: https://github.com/logdna/logdna-agent-v2
