### ISSUE TITLE
Passing LDLOGSSL=yes as an env variable

### ISSUE THREAD

**Issue by koraa** [logdna/logdna-agent#124]
Hi all!

What happens if I pass `LDLOGSSL=yes` as an environment variable to the logdna agent?
Haven't got access to a testing machine right now, but considering the line below, I would suppose SSL would be disabled, which is a bit of a usable security issue.

```
    , LOGDNA_LOGSSL: isNaN(process.env.LDLOGSSL) ? true : +process.env.LDLOGSSL
```

Well, it's just a minor inconvenience I suppose. Thanks for all your great work!

**Comment by leeliu** [comment]
Defaults to `true`.
