### ISSUE TITLE
logdna agent broken with kubernetes 1.16.0

### ISSUE THREAD

**Issue by happysalada** [logdna/logdna-agent#128]
trying to install logdna agent doesn't work with kubernetes 1.16.0

```
❯ kubectl create -f https://raw.githubusercontent.com/logdna/logdna-agent/master/logdna-agent-ds.yaml
error: unable to recognize "https://raw.githubusercontent.com/logdna/logdna-agent/master/logdna-agent-ds.yaml": no matches for kind "DaemonSet" in version "extensions/v1beta1"
```

**Comment by IdanAdar** [comment]
LogDNA must upgrade the agent to apps/v1 and add some selectors/labels for the agent to be successfully deployed w/out manual overrides by users.

**Comment by fespenido** [comment]
This will be supported in the new agent v2.1

@smusali and Connor, Can you confirm this, please?  Thanks

**Comment by smusali** [comment]
@happysalada @IdanAdar,
```
> kubeval *.yaml -o json -v 1.16.0
[
	{
		"filename": "logdna-agent-ds-master.yaml",
		"kind": "DaemonSet",
		"status": "valid",
		"errors": []
	},
	{
		"filename": "logdna-agent-ds-os.yaml",
		"kind": "DaemonSet",
		"status": "valid",
		"errors": []
	},
	{
		"filename": "logdna-agent-ds.yaml",
		"kind": "DaemonSet",
		"status": "valid",
		"errors": []
	},
	{
		"filename": "logdna-agent-v2.yaml",
		"kind": "DaemonSet",
		"status": "valid",
		"errors": []
	}
]
```

Basically, `kubeval` confirms that it's compatible with `v1.16.0`

**Comment by IdanAdar** [comment]
@smusali How is that possible?
eg for IBM, LogDNA is providing this: https://assets.eu-de.logging.cloud.ibm.com/clients/logdna-agent-ds.yaml

This YAML is using `extensions/v1beta1` which no longer exists in 1.16, it has to be `apps/v1`.
The kubernetes changelog clearly say to change this. How can it be that it works?

**Comment by andkon** [comment]
@IdanAdar thanks for your feedback. We'll be releasing new versions of the agent in the coming days that have the updated YAML.

**Comment by smusali** [comment]
Hi all!

It's already updated by #144 

Closing the issue!
