### ISSUE TITLE
Only log Kubernetes application logs

### ISSUE THREAD

**Issue by Selikoff** [logdna/logdna-agent#132]
Is it possible to configure logdna-agent-ds.yaml when installing in Kubernetes so that only the app logs are sent?  I don't need docker.log, syslog, daomon.log, kubelet.log, etc.  Right now it's sending gigabytes of data when it's only the application logs (marked by service, not file name) that I care about.

I'm guessing if I remove some of the volumes in the yaml file I can do this?  Either way, not sure what settings to change exactly.  Some help would be appreciated.

**Comment by Selikoff** [comment]
Solved it by setting this in the YAML.  Is there a cleaner way, though?

        - name: LOGDNA_EXCLUDE
          value: /var/log/daemon.log,/var/log/syslog,/var/log/auth.log,/var/log/docker.log,/var/log/lifecycle-server.log,/var/log/containers/kube-*.log,/var/log/containers/logdna-*,/var/log/containers/kubernetes-*,/var/log/containers/etcd-*,/var/log/containers/*kubelet*

**Comment by sgwilson2674** [comment]
Closing the issue. If additional questions remain, please open another issue and we’ll be sure to respond. 
If additional kubernetes questions, please visit this repo which is used for our k8s agent: https://github.com/logdna/logdna-agent-v2
