### ISSUE TITLE
Unable to start logdna-agent on RHEL

### ISSUE THREAD

**Issue by Hydrocephalic** [logdna/logdna-agent#147]
Latest version (1.6.2-1) of LogDNA Agent does not start on RHEL7 server.

These are the error messages:
```
/usr/bin/logdna-agent: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /usr/bin/logdna-agent)
/usr/bin/logdna-agent: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /usr/bin/logdna-agent)
/usr/bin/logdna-agent: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /usr/bin/logdna-agent)
Unable to start
```

LogDNA Agent version:
```
# yum list installed |grep logdna
logdna-agent.x86_64               1.6.2-1                    @logdna
```
Previous version (1.5.6-1) works perfectly.

Looking at available `GLIBCXX_*`:
```
# strings /lib64/libstdc++.so.6 | grep GLIBCXX
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_DEBUG_MESSAGE_LENGTH
```
`GLIBCXX_3.4.21` is not available.

**RHEL version**: 7.6

**Comment by andkon** [comment]
Thanks  @Hydrocephalic – it looks like we bumped the Agent's version of Node and it affected far more distros of Linux than we thought it would. We're going to be reverting the yum repo to the earlier version and changing the Node version before redeploying agent 1.6.2. A workaround for now would be to use `1.5.6-1` for now.

I'll update this card as we rebuild and redeploy the agent to the various repos.

**Comment by andkon** [comment]
New builds of the 1.6.2 version of the agent are now available, including updated .rpm packages. 

Unfortunately, we're unable to offer any ongoing support for CentOS 6; the last working version of the Agent for CentOS 6 users will be 1.5.6. I understand this far from an ideal notification process, and I regret that deprecating CentOS 6 support in 1.6.2 was the only real viable path to releasing the new version. We've learned why our communications fell apart around notifying CentOS 6 users in advance, why our testing failed to identify that CentOS 7 and Amazon Linux users would be affected, and why we were unable to simply revert or remove the latest packages from our yum repo. Together, these events compounded in ways that became serious frustrations, and we'll be working to resolve the underlying causes before we release any future versions of the agent.

For CentOS 7 users, as well as Amazon Linux users, simply re-run this command and it should pull the latest package:
`sudo yum -y install logdna-agent`
