### ISSUE TITLE
hostname variable

### ISSUE THREAD

**Issue by kimbrandt** [logdna/logdna-agent#15]
If i enter `hostname = www.example.com` it just display `www` as hostname.
Almost the same happens if i enter `hostname = "www.example.com"`, though it shows as `"www` instead.

How should I use the `hostname` variable correctly in `/etc/logdna.conf`?

**Comment by leeliu** [comment]
You should just name it the name of the host. Usually like mysql1 or web1 or something descriptive. `hostname` is totally optional and by default we read the machine's hostname. The option is mainly there if you don't like what the machine is named.
