### ISSUE TITLE
Feature Request: Add Event Level to the windows agent

### ISSUE THREAD

**Issue by ThomasUllrich666** [logdna/logdna-agent#156]
Hi Logdna Team,
right now I am not able to Identifiy the Log Level of an Windows Event in logdna. I just see something like this:
<datetime> <servername> <windowsSource> <windowsDescription>

I am not able to identify in LogDna if it is just a information, warning or an error. Can you please extend the behavior

**Comment by smusali** [comment]
@ThomasUllrich666, thanks for reporting this bug! We have already opened a ticket and will do our best to fix the bug as soon as possible.

**Comment by sgwilson2674** [comment]
We've deprecated WinEvents in the past few months and recommend NXLog. You can see documentation here: https://docs.logdna.com/docs/nxlog-for-windows
If you have more questions, please open a ticket and we'll be sure to respond.
