### ISSUE TITLE
LogDNA Agent does not have the logs from all the microservice in the pod

### ISSUE THREAD

**Issue by sam-almighty** [logdna/logdna-agent#160]
We have multiple microservices in our cluster, each microservice has its own log file under /var/log folder of the corresponding pod with the same file name. These logs are redirected to the logdna-deamon agent. However we see only the logs of one of the component and not all the component. Can someone help with this.

The DS yaml file is as below:

```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    deprecated.daemonset.template.generation: "1"
  creationTimestamp: "2020-03-09T10:34:50Z"
  generation: 1
  labels:
    app: logdna-agent
  name: logdna-agent
  namespace: default
  resourceVersion: "96436255"
  selfLink: /apis/apps/v1/namespaces/default/daemonsets/logdna-agent
  uid: f006810a-1646-40ca-b05d-168a714c31f4
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: logdna-agent
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: logdna-agent
    spec:
      containers:
      - env:
        - name: LOGDNA_AGENT_KEY
          valueFrom:
            secretKeyRef:
              key: logdna-agent-key
              name: logdna-agent-key
        - name: LDAPIHOST
          value: api.us-south.logging.cloud.ibm.com
        - name: LDLOGHOST
          value: logs.us-south.logging.cloud.ibm.com
        - name: LOGDNA_PLATFORM
          value: k8s
        image: logdna/logdna-agent:latest
        imagePullPolicy: Always
        name: logdna-agent
        resources:
          limits:
            memory: 500Mi
          requests:
            cpu: 20m
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/log
          name: varlog
        - mountPath: /var/data
          name: vardata
        - mountPath: /var/lib/docker/containers
          name: varlibdockercontainers
          readOnly: true
        - mountPath: /mnt
          name: mnt
          readOnly: true
        - mountPath: /var/run/docker.sock
          name: docker
        - mountPath: /etc/os-release
          name: osrelease
        - mountPath: /etc/logdna-hostname
          name: logdnahostname
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /var/log
          type: ""
        name: varlog
      - hostPath:
          path: /var/data
          type: ""
        name: vardata
      - hostPath:
          path: /var/lib/docker/containers
          type: ""
        name: varlibdockercontainers
      - hostPath:
          path: /mnt
          type: ""
        name: mnt
      - hostPath:
          path: /var/run/docker.sock
          type: ""
        name: docker
      - hostPath:
          path: /etc/os-release
          type: ""
        name: osrelease
      - hostPath:
          path: /etc/hostname
          type: ""
        name: logdnahostname
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 100%
    type: RollingUpdate
status:
  currentNumberScheduled: 6
  desiredNumberScheduled: 6
  numberAvailable: 6
  numberMisscheduled: 0
  numberReady: 6
  observedGeneration: 1
  updatedNumberScheduled: 6
```

I see this in one of the agents logs file:

```
2020-03-09 10:34:59 0000 [info] streaming /var/log: 44 file(s)
2020-03-09 10:40:07 0000 [info] sent 30 lines queued from earlier disconnection
2020-03-09 11:04:59 0000 [info] streaming resumed after healthcheck call
2020-03-09 11:10:10 0000 [info] sent 325 lines queued from earlier disconnection
2020-03-09 11:17:25 0000 [info] request error: Error: read ECONNRESET
2020-03-09 11:17:43 0000 [info] sent 43 lines queued from earlier disconnection
2020-03-09 11:31:06 0000 [info] sent 260 lines queued from earlier disconnection
2020-03-09 11:34:59 0000 [info] streaming resumed after healthcheck call
2020-03-09 12:04:59 0000 [info] streaming resumed after healthcheck call
2020-03-09 12:19:28 0000 [info] sent 17 lines queued from earlier disconnection
2020-03-09 12:34:59 0000 [info] streaming resumed after healthcheck call
2020-03-09 12:41:01 0000 [info] sent 21 lines queued from earlier disconnection
2020-03-09 12:59:13 0000 [info] sent 325 lines queued from earlier disconnection
2020-03-09 13:05:02 0000 [info] streaming resumed after healthcheck call
2020-03-09 13:21:41 0000 [info] sent 32 lines queued from earlier disconnection
2020-03-09 13:27:43 0000 [info] sent 9 lines queued from earlier disconnection
2020-03-09 13:28:11 0000 [info] request error: Error: read ECONNRESET
2020-03-09 13:28:27 0000 [info] sent 19 lines queued from earlier disconnection
2020-03-09 13:29:02 0000 [info] sent 22 lines queued from earlier disconnection
2020-03-09 13:29:14 0000 [info] sent 16 lines queued from earlier disconnection
2020-03-09 13:29:33 0000 [info] sent 212 lines queued from earlier disconnection
2020-03-09 13:29:47 0000 [info] sent 32 lines queued from earlier disconnection
```

Please let me know if any further information is required.

**Comment by matt-march** [comment]
hi @sam-almighty. Are you running this agent in Kubernetes? If so, our agent can't see logs written by an application in a container that are written inside the same container. To check, can you see if you can see all the expected logs with `kubectl logs`?

Additionally, please note that in Kubernetes we need your application to write out to STDOUT/STDERR for us to see the logs: https://docs.logdna.com/docs/kubernetes#section-kubernetes-compliance.

**Comment by sam-almighty** [comment]
@matt-march Yes we are running the agent on Kubernetes. As per this document (https://cloud.ibm.com/docs/Log-Analysis-with-LogDNA?topic=LogDNA-config_agent_kube_cluster )
> To configure your Kubernetes cluster to send logs to your IBM Log Analysis with LogDNA instance, you must install a logdna-agent pod on each node of your cluster. The LogDNA agent reads log files from the pod where it is installed, and forwards the log data to your LogDNA instance.

The logs should have been forwarded by the LogDNA agent. Is this not the case?

**Comment by matt-march** [comment]
@sam-almighty Sounds correct from what you've said so far. Can you confirm if you are writing to `/var/logs` in their containers or `/var/logs` in the pod(s)? And also if you are writing to `STDOUT/STDERR` in addition to the log files?

Can you see logs for your missing components with `kubectl logs`?

Additionally, can you help me understand your setup and exactly what's missing. Do you have all (expected) logs from one component, and no logs from all other components? And are all components in the same pod or the same container, or are they in different pods or different containers?

**Comment by sam-almighty** [comment]
@matt-march We have 6 kube deployments: push-server-controller, push-web-dispatcher, push-message-processor, push-events-handler, push-apns-dispatcher, push-gcm-dispatcher

Each of these have 3 pods each - they are all 1 container per pod

Each of the above deployments have volumes defined.  /var/logs/pushtrace  of each container is mounted to the host /var/logs/pushtrace directory.

According to our understanding, the content written to these files should come into LogDNA. However we see the logs of only one of the component, and we do not see it for all the other components.

**Comment by matt-march** [comment]
@sam-almighty can you also confirm you are writing to `stdout/stderr` in addition to the files?

**Comment by sam-almighty** [comment]
@matt-march Since we are not getting the logs from the files, we have additionally writing to `stdout/stderr` to get the logs onto LogDNA.

**Comment by matt-march** [comment]
@sam-almighty thanks. After additionally writing to `stdout/stderr` from your microservices is your issue resolved? 

Writing to those streams is a requirement for using the agent in Kubernetes per the [documentation on the LogDNA site](https://docs.logdna.com/docs/kubernetes#section-kubernetes-compliance). However it's unfortunately not totally clear that it is on the [IBM Cloud documentation you linked](https://cloud.ibm.com/docs/Log-Analysis-with-LogDNA?topic=LogDNA-config_agent_kube_cluster#config_agent_kube_cluster_step5). Following up to try and resolve the discrepancy.

**Comment by sam-almighty** [comment]
@matt-march So by this, you confirm that the only way to get the logs is by writing to the `stdout/stderr` stream? 

So I totally see that there is no point in logging to the file unless that is just being used as a place holder for future reference.

**Comment by sam-almighty** [comment]
@matt-march Can you please confirm on this?

**Comment by matt-march** [comment]
@sam-almighty apologies for the delay. I'm still working on confirming if writing to `stdout/stderr` is a requirement or best practice. 

In the meantime can you see all the log files, including for the missing components, if you list the files in `/var/logs/pushtrace` in the pods hosting your containers?

**Comment by sgwilson2674** [comment]
Closing the issue due to inactivity. If additional questions remain, please open another issue and we’ll be sure to respond. If additional kubernetes questions, please visit this repo which is used for our k8s agent: https://github.com/logdna/logdna-agent-v2
