### ISSUE TITLE
Windows: EBUSY: resource busy or locked

### ISSUE THREAD

**Issue by summatix** [logdna/logdna-agent#167]
I'm setting up logdna-agent on a Windows machine for a log file that is continuously written to. The program will often open the file and write to it. The writing causes a lock which interferes with reading the file's contents.

Unfortunately this leads to logdna-agent failing with the error `"0700 [error] tail error: [FILE]: Error: EBUSY: resource busy or locked, open '[FILE]'`.

I can replicate this in PowerShell using `Get-Content [FILE] -Wait`. This will stream contents until the program generating the log locks the file, causing the PowerShell command to fail.

I would expect logdna-agent to not throw an error when the file is locked and instead wait until the file isn't locked and the contents can be read.

**Comment by summatix** [comment]
The error seems to be getting thrown here: https://github.com/logdna/logdna-agent/blob/master/lib/file-utilities.js#L134

I believe what is happening is that the program is actually erasing all previous contents of the log and then writing to the same file again.

**Comment by rmcto** [comment]
I agree with summatix.

**Comment by summatix** [comment]
Maybe adding something like the following to `TailReadStream._handleError` could work:

    if (error.code === "EBUSY") {
        debug(`${this._filepath}: file locked, waiting for it to be released...`);
        this._idle += this._interval;
        this._retryInInterval();
        return;
    }

**Comment by summatix** [comment]
Just tested, and what I posted above does indeed work. I'll create a PR.

**Comment by darinspivey** [comment]
Hey guys, sorry this is a late reply, but we're doing some re-organization of this project and addressing some bugs.  On that note, we have completely re-written the existing "tail" logic to be a lossless, fault tolerant implementation.  Stay tuned soon for the announcement of what will be called `@logdna/tail-file` (we are open sourcing this solution for the public).

For now, in an effort to clean up these issues before doing some re-organizing, I'm going to go ahead and close this, but we certainly appreciate the discussion around this.  If this is still a problem with the new implementation, the suggested fix to tolerate `EBUSY` can be easily implemented.
