### ISSUE TITLE
journald logs not showing systemd service name as app name

### ISSUE THREAD

**Issue by summatix** [logdna/logdna-agent#168]
I'm setting up LogDNA with Fedora CoreOS and am using the logdna-agent's `USEJOURNALD` feature. The logs are being forwarded correctly but aren't being correctly identified inside the LogDNA view.

Logs are showing up with the `App` "podman" instead of showing the systemd service name.

This is due to this line here: https://github.com/logdna/logdna-agent/blob/master/lib/file-utilities.js#L215

The parsing is grabbing `SYSLOG_IDENTIFIER` first instead of `_SYSTEMD_UNIT`.

**Comment by smusali** [comment]
Resolved by #210 and will be released as a part of `v2.1.0`
