### ISSUE TITLE
app.logdna.com wildcard ssl issue

### ISSUE THREAD

**Issue by kenotsolutions** [logdna/logdna-agent#176]
Site: | app.logdna.com
-- | --
Certificate CN: | *.logdna.com
Certificate Authority: | Sectigo RSA Domain Validation Secure Server CA
Certificate Validity: | Not Before: Nov 26 00:00:00 2019 GMTNot After: Feb 23 23:59:59 2021 GMT

Can you check your wildcard ssl I cannot login with my credentials?

**Comment by smusali** [comment]
@kenotsolutions, we have already fixed the issue! Everything should be good to go now!

Please, let us know if you are still having the issues.

Thanks a lot!
