### ISSUE TITLE
[doc] logging-with-kubernetes-should-not-be-this-painful - page not found

### ISSUE THREAD

**Issue by prashantgupta24** [logdna/logdna-agent#177]
The URL link for the page `logging-with-kubernetes-should-not-be-this-painful` under the section: https://github.com/logdna/logdna-agent#upgrading-to-logdna-agent-20-for-kubernetes seems to be broken, it says `Page not found`.

**Comment by darinspivey** [comment]
Thank you for notifying us.  That section of the README has been re-worded.  Closing this.
