### ISSUE TITLE
Deploying on Elastic beanstalk bug

### ISSUE THREAD

**Issue by CarlChaappletree** [logdna/logdna-agent#212]
Hi,

Deploying app on EB, building fails with the following message:

Activity execution failed, because: Stopping logdna-agent.............
  Not stopped; may still be shutting down or shutdown may have failed
  Unable to stop, will not attempt to start
   (ElasticBeanstalk::ExternalInvocationError)

The weird thing is that first build fails but right after building fail, if I build the second with the same app, it works. so basically building two times in a role works.

Does anyone have an idea?

More info:
- It starts happening about 2 weeks ago.

- I use the following extension script as your docs say.
https://docs.logdna.com/docs/elastic-beanstalk

**Comment by CarlChaappletree** [comment]
I use the following extension script: 

files:
  "/home/ec2-user/logdna.sh" :
    mode: "000777"
    owner: root
    group: root
    content: |
      #!/bin/sh
      rpm --import https://repo.logdna.com/logdna.gpg
      echo "[logdna]
      name=LogDNA packages
      baseurl=https://repo.logdna.com/el6/
      enabled=1
      gpgcheck=1
      gpgkey=https://repo.logdna.com/logdna.gpg" | sudo tee /etc/yum.repos.d/logdna.repo
      yum -y install logdna-agent
      logdna-agent -k INSERT_KEY_HERE # this is your unique Ingestion Key
      # /var/log is monitored/added by default (recursively), optionally add more dirs here (remove # to uncomment the line)
      #logdna-agent -d /path/to/your/logs
      # --hostname allows you to pass your env hostname/appname to LogDNA, optionally you can change this to whatever you want (remove # to uncomment the line below)
      #logdna-agent --hostname `{"Ref": "AWSEBEnvironmentName" }`
      # -t option allows you to tag the host/app with the existing host/app name, optionally you can change this to whatever you want (remove # to uncomment the line below)
      #logdna-agent -t `{"Ref": "AWSEBEnvironmentName" }`
      chkconfig logdna-agent on
      service logdna-agent start
commands:
  01_install_logdna:
    command: "/home/ec2-user/logdna.sh"
  02_restart_logdna:
    command: "service logdna-agent restart"

**Comment by jalenplayvs** [comment]
I can confirm that we have the same issue.  Technically this should not be specific to Elastic Beanstalk, but it manifests itself very clearly as deployment failures when using Elastic Beanstalk.  Possibly a bug in the process signal handling, as if it refuses to stop if it cannot flush the logs it is buffering (or something like that).  Or maybe it just has a bug where Node has async code that is locked up and the process won't die.

Also, it would almost certainly be preferable to `kill -9` here instead of failing, which would alleviate the deployment problem:
https://github.com/logdna/logdna-agent/blob/master/tools/files/linux/init-script#L73-L75
The possibility that the agent is hung and not sending logs is still a concern, but I believe this behavior would be better regardless... and if this is simply a Node async deadlock with no other consequence, then likely `kill -9` is the only reasonable solution.

**Comment by darinspivey** [comment]
Thanks for this report.  Yes, we've received other reports of the shutdown not working on the first try (which may be a signal handling issue). We will look into it!

**Comment by timbrownsf** [comment]
Also having this issue: ```
[02_restart_logdna] : Activity execution failed, because: Stopping logdna-agent.............
  Not stopped; may still be shutting down or shutdown may have failed
  Unable to stop, will not attempt to start
   (ElasticBeanstalk::ExternalInvocationError)
```

**Comment by darinspivey** [comment]
We have tracked down the bug to be a hanging timer.  For some reason, this only hangs when running the agent as a service, but that could be a difference between the binary (`nexe` build) of the agent versus not.  Either way, the fix has been verified to work and a PR is incoming!

**Comment by timbrownsf** [comment]
Fantastic! This is causing large frustrations as every deploy (even to our staging environments) is failing so looking forward to the fix. Thank you.

**Comment by darinspivey** [comment]
We will cut a release for this by tomorrow.  Thanks to all for contributing on this.  Standby for the release...

**Comment by smusali** [comment]
`LogDNA Agent v2.1.1` patch release containing the fix has already been published. Thanks all!

**Comment by darinspivey** [comment]
@timbrownsf and @CarlChaappletree feel free to touch base and let us know if this fix has indeed solved your problem as expected.  Thanks!

**Comment by CarlChaappletree** [comment]
> @timbrownsf and @CarlChaappletree feel free to touch base and let us know if this fix has indeed solved your problem as expected. Thanks!

All seem to work fine! Thanks for the fixes!

**Comment by jalenplayvs** [comment]
I am still having this issue today with the latest release:
```
$ rpm -qa | grep logdna
logdna-agent-2.1.1-1.x86_64
```

**Comment by CarlChaappletree** [comment]
@darinspivey 

I don't see any errors I had before.

Thanks for the fixes!

**Comment by smusali** [comment]
@CarlChaappletree, @timbrownsf, @jalenplayvs's fix (#213) has been released in the newest version of the agent: `LogDNA Agent v2.1.2`

Thank y'all a lot!
