### ISSUE TITLE
No SECURE way to install Log DNA

### ISSUE THREAD

**Issue by homm** [logdna/logdna-agent#22]
```
echo "deb http://repo.logdna.com stable main" | sudo tee /etc/apt/sources.list.d/logdna.list
wget -O- http://repo.logdna.com/logdna.gpg | sudo apt-key add -
sudo apt-get update
sudo apt-get install logdna-agent < "/dev/null" # dev/null required for scripting
```

You suggest to add keys downloaded through HTTP on production server. This is ridiculous.

**Comment by baronomasia** [comment]
Hey @homm,

We really appreciate your attention to security. We do have a https link available for downloading the GPG key here: https://s3.amazonaws.com/repo.logdna.com/logdna.gpg. Let us know if you have any other feedback.

**Comment by baronomasia** [comment]
@homm I followed up with our engineering team on this issue, and it appears that [our instructions inside the web app](https://app.logdna.com/pages/add-host) use https. My guess is that we may have neglected to update one of our repos with the new instructions. I'll have the team take a look, but if you can point us to where you got those instructions, that will help expedite our search.

**Comment by homm** [comment]
I found this instruction on the releases page: https://github.com/logdna/logdna-agent/releases This is third link in google for the query "logdna setup ubuntu".

Also, you have the same issue on the front page https://logdna.com:

```
wget -qO /tmp/logdna-cli.deb http://repo.logdna.com/linux/logdna-cli.deb && sudo dpkg -i /tmp/logdna-cli.deb
```

The package is downloaded through HTTP and installed with `sudo`.

**Comment by baronomasia** [comment]
@homm Got it - we've updated the instructions from that page to use the https link I sent you earlier. As for the instructions on the front page, that is for the CLI and not for the agent - I hope that makes sense. If you have any other feedback let us know, otherwise I will close this issue tomorrow.

**Comment by homm** [comment]
> that is for the CLI and not for the agent

But this still software you offering to install to the system. The channel should be secure either package should be signed.

**Comment by baronomasia** [comment]
@homm understood, although the CLI is intended for your local machine and not your production VMs / remote hosts.

**Comment by dmitry-mukhin** [comment]
@baronomasia how is this relevant? do you think that it's ok to install software from untrusted sources on working machine?

**Comment by baronomasia** [comment]
@homm i may have failed to articulate my intention. I agree that it is best practice to install software from trusted sources. I do not, however, believe that the CLI is relevant to this GitHub issue nor is it required to be able to use our software. However, I will bring this up with our engineering team to see what we can do to get the CLI package signed and posted. In the meantime, if you wish to open an issue on our [CLI repo](https://github.com/logdna/logdna-cli), I can address your CLI-related inquiries there.
