### ISSUE TITLE
HTTP_PROXY

### ISSUE THREAD

**Issue by CommonGuy** [logdna/logdna-agent#23]
Is there a way to specify the proxy? We're behind a coorporate web proxy, and the agent doesn't seem to use the HTTP_PROXY or HTTPS_PROXY environment variables.

**Comment by leeliu** [comment]
@CommonGuy @virth Apologies for the late reply, we use the `request` which from this: https://github.com/request/request#controlling-proxy-behaviour-using-environment-variables seems to indicate that it will read `HTTP_PROXY` and `HTTPS_PROXY` env vars. Is it not working? I'm not 100% sure how to replicate this.

**Comment by CommonGuy** [comment]
@leeliu In the authentication part, you use the npm module `got`, which doesn't support proxies out of the box. Also, the `ws` module doesn't support proxies either: https://github.com/websockets/ws#how-to-connect-via-a-proxy.

You could try to set `HTTP_PROXY` or `HTTPS_PROXY` on your machine. If it still works, then it doesn't support proxies.

**Comment by virth** [comment]
@leeliu in my PR i tried to complement the proxy support. I use  https://www.npmjs.com/package/tunnel in `api-client.js` and https://www.npmjs.com/package/https-proxy-agent in `connection-manager.js` 

Would be happy if you could have a look at my [PR](https://github.com/logdna/logdna-agent/pull/25/files)

**Comment by leeliu** [comment]
We switched the internals to `request` instead of `got`. `request` should natively handle `HTTP_PROXY` and `HTTPS_PROXY`. I was originally going to finish your PR, but decided that it would be easier to just replace `got`.
