### ISSUE TITLE
How can I set "app name"?

### ISSUE THREAD

**Issue by mattfeury** [logdna/logdna-agent#29]
Hello,

LogDNA lets me filter by "app", but I don't see any way to set that value for this agent. Is there anyway I'm not seeing to do this? I can set tags and hostname, but I believe those are different

**Comment by leeliu** [comment]
Apologies for the super late reply...didn't actually originally see this.

The "app" is mapped to the filename in the agent.

**Comment by mattfeury** [comment]
ok will consider this a feature request then. other implementations of logdna allow me to specify an app name to keep all my logs and instances grouped together under a single source. not sure that filename really makes the most sense to map to app name as an app can have multiple log files. would love to see this customizable

**Comment by leeliu** [comment]
Ahh we use tags for exactly that. You can specify tags either as a whole `-t production,workers` for a particular agent or you can specify tags per path prefix using `-t production,customer1=/logs/web/cust1/web.log,customer2=/logs/web/cust2/web.log`. Does that work for your use caee?

**Comment by puneeth-k** [comment]
we are using this in ElasticBeanStalk environment in multiple of our applications. Not able to trace which log is for what app and causing lots of issues. Its making that App based Filter Unusable. 
If you can support all the options that are accepted as part of the ruby gem of REST APIs by using say 
-a => for App Name 
will be useful.

**Comment by tonyxiao** [comment]
@leeliu is there anyway to specify logdna tag for a specific pod template?

**Comment by torsorensen** [comment]
Hi,
How have people solved this in general? 
Configuring the logdna agent seems to only allow for the concept of tags, e.g. for differentiating between environments.
However, I'm looking for a decent way to separate microservices by "app" name taken from the pod or the container the pod is running in. Possibly something that can be applied on the pod template level like tonyxiao suggests.
Looking forward to hearing any interesting solutions!

**Comment by rsweetland** [comment]
Hi, just weighing in here. In my opinion, mapping `app` to the filename is a misnomer. It would make more sense to me to allow `app` to be explicitly set and add the filename as a tag.

That being said, here is an imperfect workaround if you have already committed to application name (as we have): 

Change the name of your logfile to match your app name. For example: `err.log -> logs/err/app-name`
