### ISSUE TITLE
Keep older versions in apt-get repository

### ISSUE THREAD

**Issue by shaharmor** [logdna/logdna-agent#31]
Hey,

When ever you are updating the package, you are also deleting old versions from package mangers such as apt-get, which means that if someone relies on a specific version he will have to update which is a bad user experience.

I'd prefer to update when I want, not when you want :)

**Comment by leeliu** [comment]
We use a tool called [deb-s3](https://github.com/krobertson/deb-s3) which modifies the actual repo. I'm not sure how many versions it saves (if any) other than latest.

**Comment by shaharmor** [comment]
@leeliu so you should use the `-p, [--preserve-versions], [--no-preserve-versions]` option :)

**Comment by leeliu** [comment]
Awesome thanks! Added above to our script...should start preserving from now on.
