### ISSUE TITLE
Tags specified with LOGDNA_TAGS env var aren't applied

### ISSUE THREAD

**Issue by od0** [logdna/logdna-agent#34]
Using the DaemonSet manifest located here:
https://raw.githubusercontent.com/logdna/logdna-agent/master/logdna-agent-ds.yaml

I've uncommented the lines specifying the LOGDNA_TAGS env var, and specified a few desired tags. The DaemonSet runs fine and starts pumping logs to LogDNA, but no tags are applied to the log entries.

**Comment by leeliu** [comment]
Hmmm I did this just now modifying a local version of the yaml and the new tags are searchable and working.

Perhaps something else is wrong. Can you paste your yaml? Or link to a gist? What version of Kubernetes are you running and where.

**Comment by od0** [comment]
@leeliu thanks for looking into it

- The yaml is identical to the linked LogDNA manifest, with the exception that the environment variable LOGDNA_TAGS has been set
- Client version 1.8.6, cluster version 1.8.5-gke.0

**Comment by od0** [comment]
@leeliu if there's anything I can execute from within the container to help figure this out (e.g. cat some error logs) let me know!

**Comment by leeliu** [comment]
Yeah exec into bash in any of the logdna containers and type `env` to see if the tags made it there.

**Comment by od0** [comment]
@leeliu yep the LOGDNA_TAGS env var is set

**Comment by leeliu** [comment]
Hmmmm, I don't know. The code is pretty clear... https://github.com/logdna/logdna-agent/blob/master/index.js#L182

Did you try deleting the DS and redeploying it? Maybe paste some of the startup log. Also are there any other changes made to anything logdna related?

**Comment by od0** [comment]
@leeliu yep I looked at the code at the time, seemed like it should work, I tried redeploying a few times. Weirdly, it appears that the tags are working fine now, so it may have just been some issue / delay with the tags being viewable in the dashboard. I'll go ahead and close the issue - thanks for jumping on this to support 👍
