### ISSUE TITLE
Logdna-agent suddenly switches to 127.0.0.1?

### ISSUE THREAD

**Issue by syphernl** [logdna/logdna-agent#36]
A few days ago we noticed the logs stopped coming in. The `logdna-agent` was still running, but its logs showed:

```
[180115 21:30:19] Agent restart request received, restarting...
[180115 21:30:22] logdna-agent 1.4.7 started on web01.example.com (10.10.10.10)
[180115 21:30:22] Authenticating API Key with api.logdna.com (SSL)...
[180115 21:30:22] Auth success, got token: XXXXXXXX
[180115 21:30:22] Using modes: compressed, tailmode: trs, transport: http
[180115 21:30:22] Server error: Error: connect ECONNREFUSED 127.0.0.1:443
[180115 21:30:23] Attempting to connect #1 to :443 (SSL) using XXXXXXXX...
[180115 21:30:23] Server error: Error: connect ECONNREFUSED 127.0.0.1:443
```
This went on for some time until we noticed in the interface that the logs stopped coming in. A manual restart of the agent resolved the issue and logs are coming in again.

Its unclear what requested a restart. It wasn't a manual action nor provisioning since this was outside of our normal office hours so something server-side must have likely triggered it (and logdna temporarily pointed `logs.logdna.com` to `127.0.0.1`?)

**Comment by leeliu** [comment]
Ahh, this might explain it, for a brief period, new auth were pointing to 127.0.0.1 by a misconfiguration on our end. Apologies for that.

The restart request usually only fires if the agent is using an unusual amount of memory. Are you tailing lots of files or super high volumes? Generally we test the agent at a rate of 100k loglines/s with manageable memory footprint. Though we have gotten reports where large number of files (>1000) causes issues. I would try updating the agent to 1.4.12 to see if that solves the issue.

**Comment by syphernl** [comment]
It's the first time this happened since we started using LogDNA. It might be that we are hitting some limits since these agents are running on high traffic webservers. 

We are currently on `1.4.8` for production, our testing environment was upgraded to `1.4.12` earlier. I'll do the same with production next week.

**Comment by tomaspinho** [comment]
Just saw this on two different Kubernetes nodes, had to restart both pods.

**Comment by leeliu** [comment]
Closing this and moving "agent restarting" conversation to other issue.
