### ISSUE TITLE
How to exclude some log files?

### ISSUE THREAD

**Issue by krishamoud** [logdna/logdna-agent#39]
Is it possible to exclude some services from having their logs collected?  We are using k8s with the deamonset like the tutorial suggested but one of our services is producing a lot of logs that we don't actually need.  How do we add the `exclude` to certain containers?

**Comment by n0rmz** [comment]
You can exclude specific containers directly in the ingestion rules section. 
Go to:
"Settings" -> "Ingestion" -> "Add rule"

Then go to the "Query" field and add the "container:samplecontainer" for the container you want to exclude. You may then select whether or not you want these logs to appear in the live tail or not. 

Hope this helps.

**Comment by krishamoud** [comment]
This works, thanks!
