### ISSUE TITLE
Agent doesn't work if hostname is number

### ISSUE THREAD

**Issue by krazik** [logdna/logdna-agent#40]
logdna.conf
```
hostname=123456789
```

error:
```
[180215 15:37:50] Auth error: 500: {"error":"TypeError: req.params.hostname.split is not a function","code":"ServerError","status":"error"}
```
adding a alpha letter to the hostname will solve problem.  but probably should consider casting value to string if you're gonna split on it.

👍

**Comment by leeliu** [comment]
We've added this as a bug internally awhile back when you've added this issue. Forgot to update here.
