### ISSUE TITLE
Agent keeps too many files open while reading

### ISSUE THREAD

**Issue by inarius** [logdna/logdna-agent#42]
Tail error: Y:/CIS/Interfaces/log/cisp/201801/#######.log: Error: EMFILE: too many open files, open 'Y:\CIS\Interfaces\log\cisp\201801\#######.log'

Discussed here:
https://stackoverflow.com/questions/8965606/node-and-error-emfile-too-many-open-files

I am trying to monitor many files and probably reaching an upper limit of open handles from the operating system. In my application file handles should not be left open. Some delay on a live Tail is acceptable. Perhaps this could be an option in the agent? Regardless of the approach I think that read operations above a certain limit should queue instead of endlessly opening file handles.

**Comment by leeliu** [comment]
How many files are you monitoring? Generally most servers are configured to handle upwards of 65k files. Generally for most of our customers, the number of files tailed is < 100.

**Comment by inarius** [comment]
In my case the error was appearing some time after 2K files but before 6K files. I'd guess in the 4K range. I'm monitoring a directory that I can't really change the structure of right now because it is used for other things, and I am evaluating this tool. Files are split regularly by date and there are several more than 100 files generated per day. Cleanup cannot be done to limit the number of files further at this time.

I can't understand why the files should (ideally) all be left open. NXLog has an [ActiveFiles configuration](http://nxlog-ce.sourceforge.net/nxlog-docs/en/nxlog-reference-manual.html#im_file_config_activefiles) setting that defaults to 10 files. Polling interval can be specified.

From what I understand [graceful-fs](https://github.com/isaacs/node-graceful-fs) allows a custom max_open configuration to deal with this issue, which is a setting I would love if it was configurable.

**Comment by leeliu** [comment]
I see. That's a LOT of files and will result in memory-related issues. Are you able to exclude files using `-e`? Or having a more stringent set of files? I get that may be tricky due to time-stamped filenames. For example, are 'today's files just files w/o timestamps? That would be one way to exclude all the old files that no longer have writes to them. We do support glob patterns for picking out just the files you need or excluding the ones that are selected. Would that work?

**Comment by sgwilson2674** [comment]
Closing the issue due to inactivity. If additional questions remain, please open another issue and we’ll be sure to respond.
