### ISSUE TITLE
Frequent Server Disconnection

### ISSUE THREAD

**Issue by apurandare-lifesize** [logdna/logdna-agent#45]
Mar 16 10:07:40 logdna-agent-zjqgb logdna-agent  Disconnected from server: 1006: 
Mar 16 10:07:41 logdna-agent-zjqgb logdna-agent  Attempting to connect #1 to logs.logdna.com:443 (SSL) using rkvZlflYOYG...
Mar 16 10:07:42 logdna-agent-zjqgb logdna-agent error Server error: Error: unexpected server response (401)
Mar 16 10:07:42 logdna-agent-zjqgb logdna-agent  Got 401 response, reauthenticating...
Mar 16 10:07:42 logdna-agent-zjqgb logdna-agent  Authenticating API Key with api.logdna.com (SSL)...
Mar 16 10:07:42 logdna-agent-zjqgb logdna-agent  Auth success, got token: r1Ty75pdYG
Mar 16 10:07:42 logdna-agent-zjqgb logdna-agent  Using modes: compressed, tailmode: trs, transport: http
Mar 16 10:07:43 logdna-agent-zjqgb logdna-agent  Attempting to connect #2 to logs.logdna.com:443 (SSL) using r1Ty75pdYG...
Mar 16 10:07:44 logdna-agent-zjqgb logdna-agent  Connected to logs.logdna.com:443 (52.226.69.108) (SSL)
Mar 16 10:07:44 logdna-agent-zjqgb logdna-agent  Streaming resumed: 46 file(s)
Mar 16 10:12:47 logdna-agent-zjqgb logdna-agent  Disconnected from server: 1006: 
Mar 16 10:12:48 logdna-agent-zjqgb logdna-agent  Attempting to connect #1 to logs.logdna.com:443 (SSL) using r1Ty75pdYG...
Mar 16 10:12:48 logdna-agent-zjqgb logdna-agent  Connected to logs.logdna.com:443 (52.170.85.196) (SSL)
Mar 16 10:12:48 logdna-agent-zjqgb logdna-agent  Streaming resumed: 46 file(s)
Mar 16 10:16:11 logdna-agent-zjqgb logdna-agent  Sent 2 lines queued from earlier disconnection
Mar 16 10:35:10 logdna-agent-zjqgb logdna-agent  Disconnected from server: 1006: 
Mar 16 10:35:11 logdna-agent-zjqgb logdna-agent  Attempting to connect #1 to logs.logdna.com:443 (SSL) using r1Ty75pdYG...
Mar 16 10:35:11 logdna-agent-zjqgb logdna-agent  Connected to logs.logdna.com:443 (13.82.42.30) (SSL)
Mar 16 10:35:11 logdna-agent-zjqgb logdna-agent  Streaming resumed: 46 file(s)
Mar 16 14:00:12 logdna-agent-zjqgb logdna-agent error Server error: Error: unexpected server response (401)
Mar 16 14:00:12 logdna-agent-zjqgb logdna-agent  Got 401 response, reauthenticating...
Mar 16 14:00:12 logdna-agent-zjqgb logdna-agent  Authenticating API Key with api.logdna.com (SSL)...
Mar 16 14:00:10 logdna-agent-zjqgb logdna-agent  Disconnected from server: 1006: 
Mar 16 14:00:10 logdna-agent-zjqgb logdna-agent  Sent 6 lines queued from earlier disconnection
Mar 16 14:00:13 logdna-agent-zjqgb logdna-agent  Auth success, got token: SyUgTqg-YYz
Mar 16 14:00:13 logdna-agent-zjqgb logdna-agent  Using modes: compressed, tailmode: trs, transport: http
Mar 16 14:00:14 logdna-agent-zjqgb logdna-agent  Attempting to connect #2 to logs.logdna.com:443 (SSL) using SyUgTqg-YYz...
Mar 16 14:00:14 logdna-agent-zjqgb logdna-agent  Connected to logs.logdna.com:443 (13.90.228.84) (SSL)
Mar 16 14:00:14 logdna-agent-zjqgb logdna-agent  Streaming resumed: 46 file(s)
Mar 16 14:00:11 logdna-agent-zjqgb logdna-agent  Attempting to connect #1 to logs.logdna.com:443 (SSL) using r1Ty75pdYG...
Mar 16 14:09:48 logdna-agent-zjqgb logdna-agent  Log rotated: /var/log/pods/1e7067c5-083f-11e8-8b81-0638e0799fc0/prometheus-operator_0.log by truncation
Mar 16 14:09:48 logdna-agent-zjqgb logdna-agent  Log rotated: /var/log/containers/prometheus-operator-77895958c-lcvjf_monitoring_prometheus-operator-b259a8ebe2da3e5b9781c90d1b29371431a92eea5c97650d84545938548bbd6f.log by truncation
Mar 16 15:32:54 logdna-agent-zjqgb logdna-agent  Sent 174 lines queued from earlier disconnection
Mar 16 20:44:57 logdna-agent-zjqgb logdna-agent  Sent 168 lines queued from earlier disconnection
Mar 16 23:25:40 logdna-agent-zjqgb logdna-agent  Disconnected from server: 1006: 
Mar 16 23:25:41 logdna-agent-zjqgb logdna-agent  Attempting to connect #1 to logs.logdna.com:443 (SSL) using SyUgTqg-YYz...
Mar 16 23:25:41 logdna-agent-zjqgb logdna-agent error Server error: Error: unexpected server response (401)
Mar 16 23:25:41 logdna-agent-zjqgb logdna-agent  Got 401 response, reauthenticating...

**Comment by leeliu** [comment]
Hey there, actually this is quite normal for us. Disconnects happen when we deploy new code to our ingestion endpoints. And we deploy new code almost continually throughout each day.

However, during these disconnects, no data should be lost, they're locally queued and will flush upon reconnection. You can see some of it in your logs. We also do rolling updates, so your agent could jump onto another endpoint that's slated to be killed. That usually explains the double disconnect in under a few minutes.

Does this help?

**Comment by apurandare-lifesize** [comment]
Hi Liu,

Is ingestion endpoint same for all customers or is it different for each customer.?

Can you briefly explain me about ingestion endpoint?  Does our logs will be pushed to ingestion endpoint first and then to s3 ? Just want to understand the process flow.

Is there any way to avoid these disconnects for our account?
--
Thanks and Regards,
Amrut Purandare
Cloud Systems Engineer
Lifesize

(Video)apurandare@lifesize.com<https://call.lifesizecloud.com/extension/5296127>

Blog<http://www.lifesize.com/video-conferencing-blog/> | Twitter<https://www.twitter.com/lifesizehd> | Facebook<https://www.facebook.com/lifesizehd> | LinkedIn<http://www.linkedin.com/company/lifesize-communications> | Google+<https://plus.google.com/+LifeSizeHD/posts>

**Comment by leeliu** [comment]
All customers use the same endpoints. Logs goto the endpoint before routing internally through our pipeline onto ElasticSearch. We don't push it to s3 unless you turn on s3 archiving.

As I wrote above, disconnects are the result of code deployments on our end and should result in no data loss for any agents connected to them. Is there a particular reason to avoid the disconnects from your end?

**Comment by tishma** [comment]
The exact reason why I'm adding:
`LOGDNA_LINE_EXCLUSION_REGEX=(?:logdna\-agent)`
to my setup
