### ISSUE TITLE
Build creation fails in linux

### ISSUE THREAD

**Issue by apurandare-lifesize** [logdna/logdna-agent#47]
Hi, I am trying to create a deb file in linux system using logdna source code and i am following through below doc 
https://github.com/logdna/logdna-agent/blob/master/CONTRIBUTING.md

Observed below error. Is it a bug in the source code itself
linux (build creation)

amrut@amrut-virtual-machine:~/LogDNA/logdna-agent$ grunt test

/home/amrut/LogDNA/logdna-agent/node_modules/boom/lib/index.js:5
const Hoek = require('hoek');
^^^^^
Loading "curl.js" tasks...ERROR
>> SyntaxError: Use of const in strict mode.
Loading "eslint.js" tasks...ERROR
>> SyntaxError: Use of const in strict mode.
Warning: Task "eslint" not found. Use --force to continue.

Aborted due to warnings.

**Comment by leeliu** [comment]
What host distro and version are you using to build this? What version of node is installed? You can look here for how travis does it: https://travis-ci.org/logdna/logdna-agent

**Comment by apurandare-lifesize** [comment]
Hi ,

amrut@amrut-virtual-machine:~/LogDNA/logdna-agent$ uname -a
Linux amrut-virtual-machine 4.4.0-92-generic #115~14.04.1-Ubuntu SMP Thu Aug 10 15:06:53 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
amrut@amrut-virtual-machine:~/LogDNA/logdna-agent$ node -v
v9.7.1
amrut@amrut-virtual-machine:~/LogDNA/logdna-agent$ npm -v
5.6.0


   ╭─────────────────────────────────────╮
   │                                     │
   │   Update available 5.6.0 → 5.7.1    │
   │     Run npm i -g npm to update      │
   │                                     │
   ╰─────────────────────────────────────╯

amrut@amrut-virtual-machine:~/LogDNA/logdna-agent$ nvm ls
        v0.10.3
->       v9.7.1
         system
default -> 0.10.3 (-> v0.10.3)
node -> stable (-> v9.7.1) (default)
stable -> 9.7 (-> v9.7.1) (default)
iojs -> N/A (default)
lts/* -> lts/carbon (-> N/A)
lts/argon -> v4.8.7 (-> N/A)
lts/boron -> v6.13.0 (-> N/A)
lts/carbon -> v8.9.4 (-> N/A)
amrut@amrut-virtual-machine:~/LogDNA/logdna-agent$
--
Thanks and Regards,
Amrut Purandare
Cloud Systems Engineer
Lifesize

(Video)apurandare@lifesize.com<https://call.lifesizecloud.com/extension/5296127>

Blog<http://www.lifesize.com/video-conferencing-blog/> | Twitter<https://www.twitter.com/lifesizehd> | Facebook<https://www.facebook.com/lifesizehd> | LinkedIn<http://www.linkedin.com/company/lifesize-communications> | Google+<https://plus.google.com/+LifeSizeHD/posts>

**Comment by apurandare-lifesize** [comment]
Hi Liu,

Using travis-ci grunt test successful. But failed to grunt build failed
amrut@amrut-virtual-machine:~/logdna-agent$ grunt validate
Running "eslint:target" (eslint) task

Done, without errors.
amrut@amrut-virtual-machine:~/logdna-agent$ grunt build
Running "lineremover:nukebrowser" (lineremover) task
✔ node_modules/ws/package.json (removed 0 lines)

Running "exec:nexe" (exec) task
>> Exited with code: 127.
>> /bin/sh: 1: nexe: not found
Warning: Task "exec:nexe" failed. Use --force to continue.

Aborted due to warnings.
--
Thanks and Regards,
Amrut Purandare
Cloud Systems Engineer
Lifesize

(Video)apurandare@lifesize.com<https://call.lifesizecloud.com/extension/5296127>

Blog<http://www.lifesize.com/video-conferencing-blog/> | Twitter<https://www.twitter.com/lifesizehd> | Facebook<https://www.facebook.com/lifesizehd> | LinkedIn<http://www.linkedin.com/company/lifesize-communications> | Google+<https://plus.google.com/+LifeSizeHD/posts>

**Comment by apurandare-lifesize** [comment]
Hi Liu,

Installed nexe using cmd (npm install -g nexe@1.1.2)
grunt build failed with 
Running "exec:nexe" (exec) task
----> framework => nodejs
----> downloading https://nodejs.org/dist/v5.9.0/node-v5.9.0.tar.gz

----> extracting the node source [native tar]
----> tar -xf /home/amrut/tmp/nodejs/5.9.0/nodejs-5.9.0.tar.gz -C /home/amrut/tmp/nodejs/5.9.0
----> embedResources undefined
----> resource -> /home/amrut/tmp/nodejs/5.9.0/node-v5.9.0/lib/nexeres.js
----> bundle /home/amrut/logdna-agent/index.js
----> executing browserify via API
>> events.js:154
>> throw er; // Unhandled 'error' event
>> ^
>>
>> Error: Cannot find module 'supports-color' from '/home/amrut/logdna-agent/node_modules/https-proxy-agent/node_modules/debug/src'
>>     at /home/amrut/.nvm/versions/node/v5.9.0/lib/node_modules/nexe/node_modules/browserify/node_modules/resolve/lib/async.js:48:31
>>     at processDirs (/home/amrut/.nvm/versions/node/v5.9.0/lib/node_modules/nexe/node_modules/browserify/node_modules/resolve/lib/async.js:182:39)
>>     at ondir (/home/amrut/.nvm/versions/node/v5.9.0/lib/node_modules/nexe/node_modules/browserify/node_modules/resolve/lib/async.js:197:13)
>>     at load (/home/amrut/.nvm/versions/node/v5.9.0/lib/node_modules/nexe/node_modules/browserify/node_modules/resolve/lib/async.js:80:43)
>>     at onex (/home/amrut/.nvm/versions/node/v5.9.0/lib/node_modules/nexe/node_modules/browserify/node_modules/resolve/lib/async.js:105:17)
>>     at /home/amrut/.nvm/versions/node/v5.9.0/lib/node_modules/nexe/node_modules/browserify/node_modules/resolve/lib/async.js:26:73
>> at FSReqWrap.oncomplete (fs.js:82:15)
>> Exited with code: 1.
Warning: Task "exec:nexe" failed. Use --force to continue.

Aborted due to warnings.

**Comment by leeliu** [comment]
Hmmm I haven't run the build using node 9 before. We're on node 6 LTS and the agent itself runs on node 5.9.0 (which it takes care of). Not sure why you'd be getting node module errors. Try it again using node 6 and then running `npm install` and `npm rebuild`, then try `grunt linux`.

**Comment by apurandare-lifesize** [comment]
Hi Liu,
After going through travis-cs i too installed the same versions. below is my node and npm version used and grunt test passed but build failed.

amrut@amrut-virtual-machine:~$ node -v
v5.9.0
amrut@amrut-virtual-machine:~$ npm -v
2.15.12
amrut@amrut-virtual-machine:~$

**Comment by leeliu** [comment]
What was the build error...where did it fail?

**Comment by apurandare-lifesize** [comment]
grunt build failed with
Running "exec:nexe" (exec) task
----> framework => nodejs
----> downloading https://nodejs.org/dist/v5.9.0/node-v5.9.0.tar.gz

----> extracting the node source [native tar]
----> tar -xf /home/amrut/tmp/nodejs/5.9.0/nodejs-5.9.0.tar.gz -C /home/amrut/tmp/nodejs/5.9.0
----> embedResources undefined
----> resource -> /home/amrut/tmp/nodejs/5.9.0/node-v5.9.0/lib/nexeres.js
----> bundle /home/amrut/logdna-agent/index.js
----> executing browserify via API

events.js:154
throw er; // Unhandled 'error' event
^

Error: Cannot find module 'supports-color' from '/home/amrut/logdna-agent/node_modules/https-proxy-agent/node_modules/debug/src'
at /home/amrut/.nvm/versions/node/v5.9.0/lib/node_modules/nexe/node_modules/browserify/node_modules/resolve/lib/async.js:48:31
at processDirs (/home/amrut/.nvm/versions/node/v5.9.0/lib/node_modules/nexe/node_modules/browserify/node_modules/resolve/lib/async.js:182:39)
at ondir (/home/amrut/.nvm/versions/node/v5.9.0/lib/node_modules/nexe/node_modules/browserify/node_modules/resolve/lib/async.js:197:13)
at load (/home/amrut/.nvm/versions/node/v5.9.0/lib/node_modules/nexe/node_modules/browserify/node_modules/resolve/lib/async.js:80:43)
at onex (/home/amrut/.nvm/versions/node/v5.9.0/lib/node_modules/nexe/node_modules/browserify/node_modules/resolve/lib/async.js:105:17)
at /home/amrut/.nvm/versions/node/v5.9.0/lib/node_modules/nexe/node_modules/browserify/node_modules/resolve/lib/async.js:26:73
at FSReqWrap.oncomplete (fs.js:82:15)
Exited with code: 1.
Warning: Task "exec:nexe" failed. Use --force to continue.

**Comment by leeliu** [comment]
Delete your `node_modules` folder and try again. I don't see why it would be missing modules if `npm install` was run successfully.

**Comment by apurandare-lifesize** [comment]
amrut@amrut-virtual-machine:~/LogDNA/logdna-agent$ grunt build
Running "lineremover:nukebrowser" (lineremover) task
✔ node_modules/ws/package.json (removed 0 lines)

Running "exec:nexe" (exec) task
----> framework => nodejs
----> embedResources undefined
----> resource -> /home/amrut/tmp/nodejs/5.9.0/node-v5.9.0/lib/nexeres.js
----> bundle /home/amrut/LogDNA/logdna-agent/index.js
----> executing browserify via API
>> events.js:154
>> throw er; // Unhandled 'error' event
>> ^
>>
>> Error: Cannot find module 'supports-color' from '/home/amrut/LogDNA/logdna-agent/node_modules/https-proxy-agent/node_modules/debug/src'
>>     at /home/amrut/.nvm/versions/node/v5.9.0/lib/node_modules/nexe/node_modules/browserify/node_modules/resolve/lib/async.js:48:31
>>     at processDirs (/home/amrut/.nvm/versions/node/v5.9.0/lib/node_modules/nexe/node_modules/browserify/node_modules/resolve/lib/async.js:182:39)
>>     at ondir (/home/amrut/.nvm/versions/node/v5.9.0/lib/node_modules/nexe/node_modules/browserify/node_modules/resolve/lib/async.js:197:13)
>>     at load (/home/amrut/.nvm/versions/node/v5.9.0/lib/node_modules/nexe/node_modules/browserify/node_modules/resolve/lib/async.js:80:43)
>>     at onex (/home/amrut/.nvm/versions/node/v5.9.0/lib/node_modules/nexe/node_modules/browserify/node_modules/resolve/lib/async.js:105:17)
>>     at /home/amrut/.nvm/versions/node/v5.9.0/lib/node_modules/nexe/node_modules/browserify/node_modules/resolve/lib/async.js:26:73
>> at FSReqWrap.oncomplete (fs.js:82:15)
>> Exited with code: 1.
Warning: Task "exec:nexe" failed. Use --force to continue.

Aborted due to warnings.

**Comment by apurandare-lifesize** [comment]
Is grunt build working for you?

**Comment by apurandare-lifesize** [comment]
Hi liu, 

Is grunt bulid working for you?  Can you please fix the above problem so that i can get a deb file with my changes.

Thanks,
Amrut

**Comment by leeliu** [comment]
Yeah it works well on our end, which is why I'm confused you're getting module missing errors since those are dependencies that we use, not our code direct.

Anyway Evan let me know what was going on and what you were trying to achieve. I'm gonna close this issue and continue in: https://github.com/logdna/logdna-agent/issues/46
