### ISSUE TITLE
Build creation in OSX failed

### ISSUE THREAD

**Issue by apurandare-lifesize** [logdna/logdna-agent#48]
Hi, I am trying to create a deb file in OSX system using logdna source code and i am following through below doc
https://github.com/logdna/logdna-agent/blob/master/CONTRIBUTING.md

mac

grunt test

 8 passing (4s)
  1 failing

  1) lib:file-utilities #streamAllLogs() streams file changes to a socket using TAIL_MODE trs:
     Error: Cannot find module 'mock-socket'
      at require (internal/module.js:11:18)
      at Context.<anonymous> (test/lib/file-utilities.js:118:35)

>> clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9
ln -fs out/Release/node node
----> cp /Users/apurandare/tmp/nodejs/5.9.0/node-v5.9.0/out/Release/node /Users/apurandare/GIT/logdna-agent/logdna-agent
----> copied

Running "exec:fpm_rpm" (exec) task
{:timestamp=>"2018-03-21T18:26:23.560684+0530", :message=>"Need executable 'rpmbuild' to convert dir to rpm", :level=>:error}
>> Exited with code: 1.
Warning: Task "exec:fpm_rpm" failed. Use --force to continue.

Aborted due to warnings.

**Comment by leeliu** [comment]
Each OS is needed to build packages for that OS. For example, Mac's will only build pkgs, not .deb's. Those require a linux machine. Or a docker setup locally.
