### ISSUE TITLE
Alpine based Docker image

### ISSUE THREAD

**Issue by vedant-khandelwal** [logdna/logdna-agent#54]
Hi,

The current docker image of the agent is using ubuntu as a base image. Even the latest ubuntu image has known vulnerabilities including high level vulnerabilities with packages such as glibc.

It would be good to have an image of the logdna agent that's based on Alpine, which is much more lightweight and hardened.

Thanks

**Comment by hipyhop** [comment]
I've created [PR#62](https://github.com/logdna/logdna-agent/pull/62) that builds an alpined-based image. Feel free to build it and test it and let us know how it goes.

```
git clone git@github.com:logdna/logdna-agent.git
VERSION=$(cat package.json | jq -r ".version")
docker build -t logdna-agent:${VERSION}-alpine
```

**Comment by rotten** [comment]
I'm confused as to how to test this.  How do I add logdna-agent to an existing Alpine Dockerfile?  When I try the 'docker build' command above, it builds an Ubuntu image.

**Comment by rotten** [comment]
What I was really hoping for was a .apk, so I could just do this in the existing Dockerfile

apk add --allow-untrusted /path/to/logdna-agent.apk

**Comment by hipyhop** [comment]
@rotten Apologies I didn't test the above commands properly, this should work

```
git clone git@github.com:logdna/logdna-agent.git
# Fetch this PR
git fetch origin pull/62/head:docker-alpine 
git checkout docker-alpine
VERSION=$(cat package.json | jq -r ".version")
docker build -f Dockerfile.alpine -t logdna-agent:${VERSION}-alpine .
```
This builds a Docker image based on Alpine Linux. An apk is outside of the scope of this issue.

**Comment by rotten** [comment]
Thanks!  I was able to follow your instructions above.  I get a docker image running Alpine with logdna-agent also running (as a node process).  I couldn't start the image without passing it the key:

 docker run -it -e "LOGDNA_AGENT_KEY=xxx"   ...

I bumped the node version in Dockerfile.alpine so I could get a more recent version of Alpine.  It still seems to work.  ( node:8.16.0-alpine )

**Comment by rotten** [comment]
Oh, and there is no "logdna-agent" command line tool in this image, which is not terrible, but worth pointing out.

**Comment by sgwilson2674** [comment]
Closing the issue due to inactivity. If additional questions remain, please open another issue and we’ll be sure to respond.
