### ISSUE TITLE
logdna-agent how to collector logs under appointed namespace

### ISSUE THREAD

**Issue by douzizuibang** [logdna/logdna-agent#67]
I have three namespaces in k8s cluster. As follow:

| namespace | pod |
| :------| ------: | 
| A | a1,a2,a3 | 
| B | b1,b2,b3 | 
| C | c1,c2,c3 | 

However, I only need collector logs in C namespaces use logdna-agent.

**Comment by MohammedFadin** [comment]
Thank you!

**Comment by sgwilson2674** [comment]
Closing the issue believing it to be resolved. If additional questions remain, please open another issue and we’ll be sure to respond.
