### ISSUE TITLE
Ability to exlude entire directory

### ISSUE THREAD

**Issue by raghavio** [logdna/logdna-agent#70]
I tried passing the directory to the `--exclude` parameter but it's not really working. The documentation only says it's used to exclude a file. I want to exclude an entire directory in my /var/log.

**Comment by matthew119427** [comment]
Having issues related to this, there are a LOT of logging going on in this particular server and I'd like to ignore that whole directory so I don't get any of Node's `EMFILE` errors which I'm getting now and it's literally killing the application. Does anyone have a solution for this?

**Comment by smusali** [comment]
Sorry for late response but after testing, I can confirm it is working properly as expected in `v1.6.5+`
