### ISSUE TITLE
How to determine log ingestion completion for a file?

### ISSUE THREAD

**Issue by dubee** [logdna/logdna-agent#71]
Is there anyway to see the amount of bytes the logdna agent has ingested from a log file? I need to be able to tell if the agent has finished reading all the logs in a file, so that I can rotate log files that have been fully processed.

**Comment by dubee** [comment]
Any updates on this???

**Comment by smusali** [comment]
I would suggest to use `LogDNA CLI` to tail the logs and do calculation but right now there is no way on the agent side to see the amount of bytes or lines sent to the servers.
