### ISSUE TITLE
Auth error: Error: connect ECONNREFUSED

### ISSUE THREAD

**Issue by moficodes** [logdna/logdna-agent#74]
I was trying to use logdna from IBM Cloud Logdna service. 

I was provided two commands to run in my cluster 

`kubectl create secret generic logdna-agent-key --from-literal=logdna-agent-key=***********************`

and 

`kubectl create -f https://repo.logdna.com/ibm/prod/logdna-agent-ds-us-south.yaml`

When I opened my logdna dashboard I saw nothing. 

I looked at the logs of the logdna 

```
[190220 03:09:40] logdna-agent 1.5.6 started on kube-%#%#%#%#%#%#%-w1.cloud.ibm (172.30.218.28)
[190220 03:09:40] Authenticating API Key with api.us-south.logging.cloud.ibm.com (SSL)...
[190220 03:09:40] Error connecting to /var/run/docker.sock: Error: connect ECONNREFUSED /var/run/docker.sock
[190220 03:09:40] Auth error: Error: connect ECONNREFUSED 160.**.**.**:443
```

I am not sure if this is a logdna specific problem or problem with the service in IBM Cloud.

**Comment by gregswift** [comment]
This error is around access to the /var/run/docker.sock on the underlying kubernetes worker node.  Most likely thats due to userid mapping.  I'm not sure how your IBM cluster is setup, as its possible to run it tighter than their default.  That being said I've been told that you shouldnt have to worry about this unless you are concerned about docker image tags being added to log metadata, but I could be wrong.

**Comment by moficodes** [comment]
I would not even look there if the logs were showing up in my logdna dashboard tbh. I will try again on a different cluster tomorrow to see if it was cluster setup issue.

**Comment by gregswift** [comment]
Can you tell what user the pod is running as?

**Comment by gebhardtr** [comment]
Not sure if this issue was ever resolved, but I had a similar issue when trying to connect to a logdna instance in a different region than my cluster.

**Comment by sgwilson2674** [comment]
Closing the issue due to inactivity. If additional questions remain, please open another issue and we’ll be sure to respond.
