### ISSUE TITLE
Support for milliseconds format

### ISSUE THREAD

**Issue by m0rganic** [logdna/logdna-agent#76]
It seems the agent doesn't support the ingestion of timestamps with resolution smaller than one second. 

We have a service running on k8s that logs at the microsecond level what ends up in the logdna UI is a truncated version everything down to the second level and apparently doesn't handle things after that level very well as we're seeing truncated versions of our timestamp as log line data for a given process. 

For example below is the contents of the file prior to logdna agent ingest on the k8s worker node:

```
{
  "log": "2019-02-20 00:31:40.643278,               '', (LWP  324), webrtc_cb      , observers.h:190:OnRenegotiationNeeded   , Info: \"Renegotiation needed.\"\n",
  "stream": "stdout",
  "time": "2019-02-20T06:31:40.64450639Z"
}
{
  "log": "2019-02-20 00:31:40.643796,            18-84, (LWP   30), rmq_jsonproc1  , webrtc_bridge.cpp:631:ensure_task_done_in_webrtc_signal_thread, \"Signaled by webrtc thread that task done\"\n",
  "stream": "stdout",
  "time": "2019-02-20T06:31:40.644508798Z"
}
{
  "log": "2019-02-20 00:31:40.643817,            18-84, (LWP   30), rmq_jsonproc1  , webrtc_bridge.cpp:649:webrtc_bridge     , \"Closing the peer connection\"\n",
  "stream": "stdout",
  "time": "2019-02-20T06:31:40.644511864Z"
}
```

And the corresponding line in the logdna UI shows something slightly different.. 

<img width="1365" alt="screen shot 2019-02-20 at 5 44 02 pm" src="https://user-images.githubusercontent.com/525275/53132978-29118c00-3537-11e9-85c9-b9ae65bd57a8.png">

Does anyone have a good solution to this?

**Comment by lmsurpre** [comment]
In my case, the agent was sending the full data; I just needed to change my personal preference to get ms in the LogDNA web UI:
![image](https://user-images.githubusercontent.com/5478798/76126942-717adb00-5fce-11ea-9808-59c03aeab5c6.png)

**Comment by sgwilson2674** [comment]
Question was answered. Closing.
