### ISSUE TITLE
"File does not exist, stopped tailing" for short lived k8s containers

### ISSUE THREAD

**Issue by gaieges** [logdna/logdna-agent#93]
We've got a k8s `cronjob` that runs for about 2-3 seconds or so on occasion .. and the containers hang around for around 15 min or so after the job is completed.  

We have a few other cronjobs that take a bit longer to run (hours), which seem to make it to logdna without any problems.  So thinking that the short-lived nature of the new cronjob is the culprit.

For some reason these logs aren't making it to logdna.  Looking at the logs for logdna-agent we see:
```
[190418 17:24:10] File does not exist, stopped tailing: /[redacted]/8c88fdc57700bfe9e3e1523d0e49067dcbe291ac2ec77b2fab827905f10b82fd.log after 300000ms
```

Is there anyway to work around this?

K8s (AKS): 1.12.6
logdna-agent 1.5.6

**Comment by sgwilson2674** [comment]
Closing the issue due to inactivity. If additional questions remain, please open another issue and we’ll be sure to respond. 
If additional kubernetes questions, please visit this repo which is used for our k8s agent: https://github.com/logdna/logdna-agent-v2

**Comment by gaieges** [comment]
> Closing the issue due to inactivity

What activity was expected?
