### ISSUE TITLE
/etc/os-release is not present on all systems

### ISSUE THREAD

**Issue by moltar** [logdna/logdna-agent#97]
The `/etc/os-release` file is not present on all systems.

Notable `rancher/k3s` image, that is gaining popularity does not have this file and deployment fails.

I am using `rancher/k3s` for testing deployments, but in production this file exists.

So I am not sure how to handle this gracefully.

Mainly opened this up for discussions. I don't think this is a bug in `logdna-agent`. But if there is a way to adjust `logdna-agent`, then that would be a welcome change too.

**Comment by sgwilson2674** [comment]
Closing. This was resolved in the latest release of the agent.
